export const SET_WON_ROOM_AUCTION = "SET_WON_ROOM_AUCTION";
export const ADD_WON_ROOM_AUCTION = "ADD_WON_ROOM_AUCTION";
export const CANCEL_PAY_WON_AUCTION = "CANCEL_PAY_WON_AUCTION";
export const PAID_WON_AUCTION = "PAID_WON_AUCTION";
export const SET_OWN_ROOM = "SET_OWN_ROOM";
