export const SET_ROOM = "SET_ROOM";
export const SET_GAME_PRICE = "SET_GAME_PRICE";
export const SET_TOTAL_CARDS_COUNT = "SET_TOTAL_CARDS_COUNT";
export const SET_CALLED_NUMBERS = "SET_CALLED_NUMBERS";
export const SET_LAST_NUMBER = "SET_LAST_NUMBER";
export const SET_WINNERS = "SET_WINNERS";
export const SET_WINNER_EARNING = "SET_WINNER_EARNING";
